pub const dos_type = @import("./DOtherSideTypes.zig");

pub extern fn dos_qcoreapplication_application_dir_path() [*c]u8;
pub extern fn dos_qcoreapplication_process_events(flags: dos_type.DosQEventLoopProcessEventFlag) void;
pub extern fn dos_qcoreapplication_process_events_timed(flags: dos_type.DosQEventLoopProcessEventFlag, ms: c_int) void;
pub extern fn dos_qguiapplication_create() void;
pub extern fn dos_qguiapplication_exec() void;
pub extern fn dos_qguiapplication_quit() void;
pub extern fn dos_qguiapplication_delete() void;
pub extern fn dos_qapplication_create() void;
pub extern fn dos_qapplication_exec() void;
pub extern fn dos_qapplication_quit() void;
pub extern fn dos_qapplication_delete() void;
pub extern fn dos_qqmlapplicationengine_create() ?*dos_type.DosQQmlApplicationEngine;
pub extern fn dos_qqmlapplicationengine_load(vptr: ?*dos_type.DosQQmlApplicationEngine, filename: [*c]const u8) void;
pub extern fn dos_qqmlapplicationengine_load_url(vptr: ?*dos_type.DosQQmlApplicationEngine, url: ?*dos_type.DosQUrl) void;
pub extern fn dos_qqmlapplicationengine_load_data(vptr: ?*dos_type.DosQQmlApplicationEngine, data: [*c]const u8) void;
pub extern fn dos_qqmlapplicationengine_add_import_path(vptr: ?*dos_type.DosQQmlApplicationEngine, path: [*c]const u8) void;
pub extern fn dos_qqmlapplicationengine_context(vptr: ?*dos_type.DosQQmlApplicationEngine) ?*dos_type.DosQQmlContext;
pub extern fn dos_qqmlapplicationengine_addImageProvider(vptr: ?*dos_type.DosQQmlApplicationEngine, name: [*c]const u8, vptr_i: ?*dos_type.DosQQuickImageProvider) void;
pub extern fn dos_qqmlapplicationengine_delete(vptr: ?*dos_type.DosQQmlApplicationEngine) void;
pub extern fn dos_qquickimageprovider_create(callback: dos_type.RequestPixmapCallback) ?*dos_type.DosQQuickImageProvider;
pub extern fn dos_qquickimageprovider_delete(vptr: ?*dos_type.DosQQuickImageProvider) void;
pub extern fn dos_qpixmap_create(...) ?*dos_type.DosPixmap;
pub extern fn dos_qpixmap_create_qpixmap(other: ?*const dos_type.DosPixmap) ?*dos_type.DosPixmap;
pub extern fn dos_qpixmap_create_width_and_height(width: c_int, height: c_int) ?*dos_type.DosPixmap;
pub extern fn dos_qpixmap_delete(vptr: ?*dos_type.DosPixmap) void;
pub extern fn dos_qpixmap_load(vptr: ?*dos_type.DosPixmap, filepath: [*c]const u8, format: [*c]const u8) void;
pub extern fn dos_qpixmap_loadFromData(vptr: ?*dos_type.DosPixmap, data: [*c]const u8, len: c_uint) void;
pub extern fn dos_qpixmap_fill(vptr: ?*dos_type.DosPixmap, r: u8, g: u8, b: u8, a: u8) void;
pub extern fn dos_qpixmap_assign(vptr: ?*dos_type.DosPixmap, other: ?*const dos_type.DosPixmap) void;
pub extern fn dos_qpixmap_isNull(vptr: ?*dos_type.DosPixmap) bool;
pub extern fn dos_qquickstyle_set_style(style: [*c]const u8) void;
pub extern fn dos_qquickstyle_set_fallback_style(style: [*c]const u8) void;
pub extern fn dos_qquickview_create() ?*dos_type.DosQQuickView;
pub extern fn dos_qquickview_show(vptr: ?*dos_type.DosQQuickView) void;
pub extern fn dos_qquickview_source(vptr: ?*const dos_type.DosQQuickView) [*c]u8;
pub extern fn dos_qquickview_set_source_url(vptr: ?*dos_type.DosQQuickView, url: ?*dos_type.DosQUrl) void;
pub extern fn dos_qquickview_set_source(vptr: ?*dos_type.DosQQuickView, filename: [*c]const u8) void;
pub extern fn dos_qquickview_set_resize_mode(vptr: ?*dos_type.DosQQuickView, resizeMode: c_int) void;
pub extern fn dos_qquickview_delete(vptr: ?*dos_type.DosQQuickView) void;
pub extern fn dos_qquickview_rootContext(vptr: ?*dos_type.DosQQuickView) ?*dos_type.DosQQmlContext;
pub extern fn dos_qqmlcontext_baseUrl(vptr: ?*const dos_type.DosQQmlContext) [*c]u8;
pub extern fn dos_qqmlcontext_setcontextproperty(vptr: ?*dos_type.DosQQmlContext, name: [*c]const u8, value: ?*dos_type.DosQVariant) void;
pub extern fn dos_chararray_delete(ptr: [*c]u8) void;
pub extern fn dos_qvariantarray_delete(ptr: [*c]dos_type.DosQVariantArray) void;
pub extern fn dos_qvariant_create() ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_create_int(value: c_int) ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_create_bool(value: bool) ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_create_string(value: [*c]const u8) ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_create_qobject(value: ?*dos_type.DosQObject) ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_create_qvariant(value: ?*const dos_type.DosQVariant) ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_create_float(value: f32) ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_create_double(value: f64) ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_create_array(size: c_int, array: [*c]?*dos_type.DosQVariant) ?*dos_type.DosQVariant;
pub extern fn dos_qvariant_setInt(vptr: ?*dos_type.DosQVariant, value: c_int) void;
pub extern fn dos_qvariant_setBool(vptr: ?*dos_type.DosQVariant, value: bool) void;
pub extern fn dos_qvariant_setFloat(vptr: ?*dos_type.DosQVariant, value: f32) void;
pub extern fn dos_qvariant_setDouble(vptr: ?*dos_type.DosQVariant, value: f64) void;
pub extern fn dos_qvariant_setString(vptr: ?*dos_type.DosQVariant, value: [*c]const u8) void;
pub extern fn dos_qvariant_setQObject(vptr: ?*dos_type.DosQVariant, value: ?*dos_type.DosQObject) void;
pub extern fn dos_qvariant_setArray(vptr: ?*dos_type.DosQVariant, size: c_int, array: [*c]?*dos_type.DosQVariant) void;
pub extern fn dos_qvariant_isnull(vptr: ?*const dos_type.DosQVariant) bool;
pub extern fn dos_qvariant_delete(vptr: ?*dos_type.DosQVariant) void;
pub extern fn dos_qvariant_assign(vptr: ?*dos_type.DosQVariant, other: ?*const dos_type.DosQVariant) void;
pub extern fn dos_qvariant_toInt(vptr: ?*const dos_type.DosQVariant) c_int;
pub extern fn dos_qvariant_toBool(vptr: ?*const dos_type.DosQVariant) bool;
pub extern fn dos_qvariant_toString(vptr: ?*const dos_type.DosQVariant) [*c]u8;
pub extern fn dos_qvariant_toFloat(vptr: ?*const dos_type.DosQVariant) f32;
pub extern fn dos_qvariant_toDouble(vptr: ?*const dos_type.DosQVariant) f64;
pub extern fn dos_qvariant_toArray(vptr: ?*const dos_type.DosQVariant) [*c]dos_type.DosQVariantArray;
pub extern fn dos_qvariant_toQObject(vptr: ?*const dos_type.DosQVariant) ?*dos_type.DosQObject;
pub extern fn dos_qmetaobject_create(superClassMetaObject: ?*dos_type.DosQMetaObject, className: [*c]const u8, signalDefinitions: [*c]const dos_type.SignalDefinitions, slotDefinitions: [*c]const dos_type.SlotDefinitions, propertyDefinitions: [*c]const dos_type.PropertyDefinitions) ?*dos_type.DosQMetaObject;
pub extern fn dos_qmetaobject_delete(vptr: ?*dos_type.DosQMetaObject) void;
pub extern fn dos_qabstractlistmodel_qmetaobject() ?*dos_type.DosQMetaObject;
pub extern fn dos_qabstractlistmodel_create(callbackObject: ?*anyopaque, metaObject: ?*dos_type.DosQMetaObject, dObjectCallback: dos_type.DObjectCallback, callbacks: [*c]dos_type.DosQAbstractItemModelCallbacks) ?*dos_type.DosQAbstractListModel;
pub extern fn dos_qmetaobject_invoke_method(context: ?*dos_type.DosQObject, callback: ?fn (?*dos_type.DosQObject, ?*anyopaque) callconv(.C) void, data: ?*anyopaque, connection_type: dos_type.DosQtConnectionType) bool;
pub extern fn dos_qabstractlistmodel_index(vptr: ?*dos_type.DosQAbstractListModel, row: c_int, column: c_int, parent: ?*dos_type.DosQModelIndex) ?*dos_type.DosQModelIndex;
pub extern fn dos_qabstractlistmodel_parent(vptr: ?*dos_type.DosQAbstractListModel, child: ?*dos_type.DosQModelIndex) ?*dos_type.DosQModelIndex;
pub extern fn dos_qabstractlistmodel_columnCount(vptr: ?*dos_type.DosQAbstractListModel, parent: ?*dos_type.DosQModelIndex) c_int;
pub extern fn dos_qabstracttablemodel_qmetaobject() ?*dos_type.DosQMetaObject;
pub extern fn dos_qabstracttablemodel_create(callbackObject: ?*anyopaque, metaObject: ?*dos_type.DosQMetaObject, dObjectCallback: dos_type.DObjectCallback, callbacks: [*c]dos_type.DosQAbstractItemModelCallbacks) ?*dos_type.DosQAbstractTableModel;
pub extern fn dos_qabstracttablemodel_index(vptr: ?*dos_type.DosQAbstractTableModel, row: c_int, column: c_int, parent: ?*dos_type.DosQModelIndex) ?*dos_type.DosQModelIndex;
pub extern fn dos_qabstracttablemodel_parent(vptr: ?*dos_type.DosQAbstractTableModel, child: ?*dos_type.DosQModelIndex) ?*dos_type.DosQModelIndex;
pub extern fn dos_qabstractitemmodel_qmetaobject() ?*dos_type.DosQMetaObject;
pub extern fn dos_qabstractitemmodel_create(callbackObject: ?*anyopaque, metaObject: ?*dos_type.DosQMetaObject, dObjectCallback: dos_type.DObjectCallback, callbacks: [*c]dos_type.DosQAbstractItemModelCallbacks) ?*dos_type.DosQAbstractItemModel;
pub extern fn dos_qabstractitemmodel_setData(vptr: ?*dos_type.DosQAbstractItemModel, index: ?*dos_type.DosQModelIndex, data: ?*dos_type.DosQVariant, role: c_int) bool;
pub extern fn dos_qabstractitemmodel_roleNames(vptr: ?*dos_type.DosQAbstractItemModel) ?*dos_type.DosQHashIntQByteArray;
pub extern fn dos_qabstractitemmodel_flags(vptr: ?*dos_type.DosQAbstractItemModel, index: ?*dos_type.DosQModelIndex) c_int;
pub extern fn dos_qabstractitemmodel_headerData(vptr: ?*dos_type.DosQAbstractItemModel, section: c_int, orientation: c_int, role: c_int) ?*dos_type.DosQVariant;
pub extern fn dos_qabstractitemmodel_hasChildren(vptr: ?*dos_type.DosQAbstractItemModel, parentIndex: ?*dos_type.DosQModelIndex) bool;
pub extern fn dos_qabstractitemmodel_hasIndex(vptr: ?*dos_type.DosQAbstractItemModel, row: c_int, column: c_int, dosParentIndex: ?*dos_type.DosQModelIndex) bool;
pub extern fn dos_qabstractitemmodel_canFetchMore(vptr: ?*dos_type.DosQAbstractItemModel, parentIndex: ?*dos_type.DosQModelIndex) bool;
pub extern fn dos_qabstractitemmodel_fetchMore(vptr: ?*dos_type.DosQAbstractItemModel, parentIndex: ?*dos_type.DosQModelIndex) void;
pub extern fn dos_qabstractitemmodel_beginInsertRows(vptr: ?*dos_type.DosQAbstractItemModel, parent: ?*dos_type.DosQModelIndex, first: c_int, last: c_int) void;
pub extern fn dos_qabstractitemmodel_endInsertRows(vptr: ?*dos_type.DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_beginRemoveRows(vptr: ?*dos_type.DosQAbstractItemModel, parent: ?*dos_type.DosQModelIndex, first: c_int, last: c_int) void;
pub extern fn dos_qabstractitemmodel_endRemoveRows(vptr: ?*dos_type.DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_beginInsertColumns(vptr: ?*dos_type.DosQAbstractItemModel, parent: ?*dos_type.DosQModelIndex, first: c_int, last: c_int) void;
pub extern fn dos_qabstractitemmodel_endInsertColumns(vptr: ?*dos_type.DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_beginRemoveColumns(vptr: ?*dos_type.DosQAbstractItemModel, parent: ?*dos_type.DosQModelIndex, first: c_int, last: c_int) void;
pub extern fn dos_qabstractitemmodel_endRemoveColumns(vptr: ?*dos_type.DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_beginResetModel(vptr: ?*dos_type.DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_endResetModel(vptr: ?*dos_type.DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_dataChanged(vptr: ?*dos_type.DosQAbstractItemModel, topLeft: ?*const dos_type.DosQModelIndex, bottomRight: ?*const dos_type.DosQModelIndex, rolesPtr: [*c]c_int, rolesLength: c_int) void;
pub extern fn dos_qabstractitemmodel_createIndex(vptr: ?*dos_type.DosQAbstractItemModel, row: c_int, column: c_int, data: ?*anyopaque) ?*dos_type.DosQModelIndex;
pub extern fn dos_qobject_qmetaobject() ?*dos_type.DosQMetaObject;
pub extern fn dos_qobject_create(dObjectPointer: ?*anyopaque, metaObject: ?*dos_type.DosQMetaObject, dObjectCallback: dos_type.DObjectCallback) ?*dos_type.DosQObject;
pub extern fn dos_qobject_signal_emit(vptr: ?*dos_type.DosQObject, name: [*c]const u8, parametersCount: c_int, parameters: [*c]?*anyopaque) void;
pub extern fn dos_qobject_signal_connect(senderVPtr: ?*dos_type.DosQObject, signal: [*c]const u8, receiverVPtr: ?*dos_type.DosQObject, method: [*c]const u8, @"type": c_int) bool;
pub extern fn dos_qobject_signal_disconnect(senderVPtr: ?*dos_type.DosQObject, signal: [*c]const u8, receiverVPtr: ?*dos_type.DosQObject, method: [*c]const u8) bool;
pub extern fn dos_qobject_objectName(vptr: ?*const dos_type.DosQObject) [*c]u8;
pub extern fn dos_qobject_setObjectName(vptr: ?*dos_type.DosQObject, name: [*c]const u8) void;
pub extern fn dos_qobject_delete(vptr: ?*dos_type.DosQObject) void;
pub extern fn dos_qobject_deleteLater(vptr: ?*dos_type.DosQObject) void;
pub extern fn dos_qobject_property(vptr: ?*dos_type.DosQObject, propertyName: [*c]const u8) ?*dos_type.DosQVariant;
pub extern fn dos_qobject_setProperty(vptr: ?*dos_type.DosQObject, propertyName: [*c]const u8, value: ?*dos_type.DosQVariant) bool;
pub extern fn dos_slot_macro(str: [*c]const u8) [*c]u8;
pub extern fn dos_signal_macro(str: [*c]const u8) [*c]u8;
pub extern fn dos_qobject_disconnect_static(sender: ?*dos_type.DosQObject, signal: [*c]const u8, receiver: ?*dos_type.DosQObject, slot: [*c]const u8) void;
pub extern fn dos_qmodelindex_create() ?*dos_type.DosQModelIndex;
pub extern fn dos_qmodelindex_create_qmodelindex(index: ?*dos_type.DosQModelIndex) ?*dos_type.DosQModelIndex;
pub extern fn dos_qobject_connect_static(sender: ?*dos_type.DosQObject, signal: [*c]const u8, receiver: ?*dos_type.DosQObject, slot: [*c]const u8, connection_type: dos_type.DosQtConnectionType) void;
pub extern fn dos_qmodelindex_delete(vptr: ?*dos_type.DosQModelIndex) void;
pub extern fn dos_qmodelindex_row(vptr: ?*const dos_type.DosQModelIndex) c_int;
pub extern fn dos_qmodelindex_column(vptr: ?*const dos_type.DosQModelIndex) c_int;
pub extern fn dos_qmodelindex_isValid(vptr: ?*const dos_type.DosQModelIndex) bool;
pub extern fn dos_qmodelindex_data(vptr: ?*const dos_type.DosQModelIndex, role: c_int) ?*dos_type.DosQVariant;
pub extern fn dos_qmodelindex_parent(vptr: ?*const dos_type.DosQModelIndex) ?*dos_type.DosQModelIndex;
pub extern fn dos_qmodelindex_child(vptr: ?*const dos_type.DosQModelIndex, row: c_int, column: c_int) ?*dos_type.DosQModelIndex;
pub extern fn dos_qmodelindex_sibling(vptr: ?*const dos_type.DosQModelIndex, row: c_int, column: c_int) ?*dos_type.DosQModelIndex;
pub extern fn dos_qmodelindex_assign(l: ?*dos_type.DosQModelIndex, r: ?*const dos_type.DosQModelIndex) void;
pub extern fn dos_qmodelindex_internalPointer(vptr: ?*dos_type.DosQModelIndex) ?*anyopaque;
pub extern fn dos_qhash_int_qbytearray_create() ?*dos_type.DosQHashIntQByteArray;
pub extern fn dos_qhash_int_qbytearray_delete(vptr: ?*dos_type.DosQHashIntQByteArray) void;
pub extern fn dos_qhash_int_qbytearray_insert(vptr: ?*dos_type.DosQHashIntQByteArray, key: c_int, value: [*c]const u8) void;
pub extern fn dos_qhash_int_qbytearray_value(vptr: ?*const dos_type.DosQHashIntQByteArray, key: c_int) [*c]u8;
pub extern fn dos_qresource_register(filename: [*c]const u8) void;
pub extern fn dos_qurl_create(url: [*c]const u8, parsingMode: c_int) ?*dos_type.DosQUrl;
pub extern fn dos_qurl_delete(vptr: ?*dos_type.DosQUrl) void;
pub extern fn dos_qurl_to_string(vptr: ?*const dos_type.DosQUrl) [*c]u8;
pub extern fn dos_qurl_isValid(vptr: ?*const dos_type.DosQUrl) bool;
pub extern fn dos_qdeclarative_qmlregistertype(qmlRegisterType: [*c]const dos_type.QmlRegisterType) c_int;
pub extern fn dos_qdeclarative_qmlregistersingletontype(qmlRegisterType: [*c]const dos_type.QmlRegisterType) c_int;
pub extern fn dos_qpointer_create(object: ?*dos_type.DosQObject) ?*dos_type.DosQPointer;
pub extern fn dos_qpointer_delete(self: ?*dos_type.DosQPointer) void;
pub extern fn dos_qpointer_is_null(self: ?*dos_type.DosQPointer) bool;
pub extern fn dos_qpointer_clear(self: ?*dos_type.DosQPointer) void;
pub extern fn dos_qpointer_data(self: ?*dos_type.DosQPointer) ?*dos_type.DosQObject;
