usingnamespace @import("DOtherSideTypes.zig");

pub extern fn dos_qcoreapplication_application_dir_path() [*c]u8;
pub extern fn dos_qcoreapplication_process_events(flags: enum_DosQEventLoopProcessEventFlag) void;
pub extern fn dos_qcoreapplication_process_events_timed(flags: enum_DosQEventLoopProcessEventFlag, ms: c_int) void;
pub extern fn dos_qguiapplication_create() void;
pub extern fn dos_qguiapplication_exec() void;
pub extern fn dos_qguiapplication_quit() void;
pub extern fn dos_qguiapplication_delete() void;
pub extern fn dos_qapplication_create() void;
pub extern fn dos_qapplication_exec() void;
pub extern fn dos_qapplication_quit() void;
pub extern fn dos_qapplication_delete() void;
pub extern fn dos_qqmlapplicationengine_create() ?*DosQQmlApplicationEngine;
pub extern fn dos_qqmlapplicationengine_load(vptr: ?*DosQQmlApplicationEngine, filename: [*c]const u8) void;
pub extern fn dos_qqmlapplicationengine_load_url(vptr: ?*DosQQmlApplicationEngine, url: ?*DosQUrl) void;
pub extern fn dos_qqmlapplicationengine_load_data(vptr: ?*DosQQmlApplicationEngine, data: [*c]const u8) void;
pub extern fn dos_qqmlapplicationengine_add_import_path(vptr: ?*DosQQmlApplicationEngine, path: [*c]const u8) void;
pub extern fn dos_qqmlapplicationengine_context(vptr: ?*DosQQmlApplicationEngine) ?*DosQQmlContext;
pub extern fn dos_qqmlapplicationengine_addImageProvider(vptr: ?*DosQQmlApplicationEngine, name: [*c]const u8, vptr_i: ?*DosQQuickImageProvider) void;
pub extern fn dos_qqmlapplicationengine_delete(vptr: ?*DosQQmlApplicationEngine) void;
pub extern fn dos_qquickimageprovider_create(callback: RequestPixmapCallback) ?*DosQQuickImageProvider;
pub extern fn dos_qquickimageprovider_delete(vptr: ?*DosQQuickImageProvider) void;
pub extern fn dos_qpixmap_create(...) ?*DosPixmap;
pub extern fn dos_qpixmap_create_qpixmap(other: ?*const DosPixmap) ?*DosPixmap;
pub extern fn dos_qpixmap_create_width_and_height(width: c_int, height: c_int) ?*DosPixmap;
pub extern fn dos_qpixmap_delete(vptr: ?*DosPixmap) void;
pub extern fn dos_qpixmap_load(vptr: ?*DosPixmap, filepath: [*c]const u8, format: [*c]const u8) void;
pub extern fn dos_qpixmap_loadFromData(vptr: ?*DosPixmap, data: [*c]const u8, len: c_uint) void;
pub extern fn dos_qpixmap_fill(vptr: ?*DosPixmap, r: u8, g: u8, b: u8, a: u8) void;
pub extern fn dos_qpixmap_assign(vptr: ?*DosPixmap, other: ?*const DosPixmap) void;
pub extern fn dos_qpixmap_isNull(vptr: ?*DosPixmap) bool;
pub extern fn dos_qquickstyle_set_style(style: [*c]const u8) void;
pub extern fn dos_qquickstyle_set_fallback_style(style: [*c]const u8) void;
pub extern fn dos_qquickview_create() ?*DosQQuickView;
pub extern fn dos_qquickview_show(vptr: ?*DosQQuickView) void;
pub extern fn dos_qquickview_source(vptr: ?*const DosQQuickView) [*c]u8;
pub extern fn dos_qquickview_set_source_url(vptr: ?*DosQQuickView, url: ?*DosQUrl) void;
pub extern fn dos_qquickview_set_source(vptr: ?*DosQQuickView, filename: [*c]const u8) void;
pub extern fn dos_qquickview_set_resize_mode(vptr: ?*DosQQuickView, resizeMode: c_int) void;
pub extern fn dos_qquickview_delete(vptr: ?*DosQQuickView) void;
pub extern fn dos_qquickview_rootContext(vptr: ?*DosQQuickView) ?*DosQQmlContext;
pub extern fn dos_qqmlcontext_baseUrl(vptr: ?*const DosQQmlContext) [*c]u8;
pub extern fn dos_qqmlcontext_setcontextproperty(vptr: ?*DosQQmlContext, name: [*c]const u8, value: ?*DosQVariant) void;
pub extern fn dos_chararray_delete(ptr: [*c]u8) void;
pub extern fn dos_qvariantarray_delete(ptr: [*c]DosQVariantArray) void;
pub extern fn dos_qvariant_create() ?*DosQVariant;
pub extern fn dos_qvariant_create_int(value: c_int) ?*DosQVariant;
pub extern fn dos_qvariant_create_bool(value: bool) ?*DosQVariant;
pub extern fn dos_qvariant_create_string(value: [*c]const u8) ?*DosQVariant;
pub extern fn dos_qvariant_create_qobject(value: ?*DosQObject) ?*DosQVariant;
pub extern fn dos_qvariant_create_qvariant(value: ?*const DosQVariant) ?*DosQVariant;
pub extern fn dos_qvariant_create_float(value: f32) ?*DosQVariant;
pub extern fn dos_qvariant_create_double(value: f64) ?*DosQVariant;
pub extern fn dos_qvariant_create_array(size: c_int, array: [*c]?*DosQVariant) ?*DosQVariant;
pub extern fn dos_qvariant_setInt(vptr: ?*DosQVariant, value: c_int) void;
pub extern fn dos_qvariant_setBool(vptr: ?*DosQVariant, value: bool) void;
pub extern fn dos_qvariant_setFloat(vptr: ?*DosQVariant, value: f32) void;
pub extern fn dos_qvariant_setDouble(vptr: ?*DosQVariant, value: f64) void;
pub extern fn dos_qvariant_setString(vptr: ?*DosQVariant, value: [*c]const u8) void;
pub extern fn dos_qvariant_setQObject(vptr: ?*DosQVariant, value: ?*DosQObject) void;
pub extern fn dos_qvariant_setArray(vptr: ?*DosQVariant, size: c_int, array: [*c]?*DosQVariant) void;
pub extern fn dos_qvariant_isnull(vptr: ?*const DosQVariant) bool;
pub extern fn dos_qvariant_delete(vptr: ?*DosQVariant) void;
pub extern fn dos_qvariant_assign(vptr: ?*DosQVariant, other: ?*const DosQVariant) void;
pub extern fn dos_qvariant_toInt(vptr: ?*const DosQVariant) c_int;
pub extern fn dos_qvariant_toBool(vptr: ?*const DosQVariant) bool;
pub extern fn dos_qvariant_toString(vptr: ?*const DosQVariant) [*c]u8;
pub extern fn dos_qvariant_toFloat(vptr: ?*const DosQVariant) f32;
pub extern fn dos_qvariant_toDouble(vptr: ?*const DosQVariant) f64;
pub extern fn dos_qvariant_toArray(vptr: ?*const DosQVariant) [*c]DosQVariantArray;
pub extern fn dos_qvariant_toQObject(vptr: ?*const DosQVariant) ?*DosQObject;
pub extern fn dos_qmetaobject_create(superClassMetaObject: ?*DosQMetaObject, className: [*c]const u8, signalDefinitions: [*c]const SignalDefinitions, slotDefinitions: [*c]const SlotDefinitions, propertyDefinitions: [*c]const PropertyDefinitions) ?*DosQMetaObject;
pub extern fn dos_qmetaobject_delete(vptr: ?*DosQMetaObject) void;
pub extern fn dos_qmetaobject_invoke_method(context: ?*DosQObject, callback: ?fn (?*DosQObject, ?*c_void) callconv(.C) void, data: ?*c_void, connection_type: enum_DosQtConnectionType) bool;
pub extern fn dos_qabstractlistmodel_qmetaobject() ?*DosQMetaObject;
pub extern fn dos_qabstractlistmodel_create(callbackObject: ?*c_void, metaObject: ?*DosQMetaObject, dObjectCallback: DObjectCallback, callbacks: [*c]DosQAbstractItemModelCallbacks) ?*DosQAbstractListModel;
pub extern fn dos_qabstractlistmodel_index(vptr: ?*DosQAbstractListModel, row: c_int, column: c_int, parent: ?*DosQModelIndex) ?*DosQModelIndex;
pub extern fn dos_qabstractlistmodel_parent(vptr: ?*DosQAbstractListModel, child: ?*DosQModelIndex) ?*DosQModelIndex;
pub extern fn dos_qabstractlistmodel_columnCount(vptr: ?*DosQAbstractListModel, parent: ?*DosQModelIndex) c_int;
pub extern fn dos_qabstracttablemodel_qmetaobject() ?*DosQMetaObject;
pub extern fn dos_qabstracttablemodel_create(callbackObject: ?*c_void, metaObject: ?*DosQMetaObject, dObjectCallback: DObjectCallback, callbacks: [*c]DosQAbstractItemModelCallbacks) ?*DosQAbstractTableModel;
pub extern fn dos_qabstracttablemodel_index(vptr: ?*DosQAbstractTableModel, row: c_int, column: c_int, parent: ?*DosQModelIndex) ?*DosQModelIndex;
pub extern fn dos_qabstracttablemodel_parent(vptr: ?*DosQAbstractTableModel, child: ?*DosQModelIndex) ?*DosQModelIndex;
pub extern fn dos_qabstractitemmodel_qmetaobject() ?*DosQMetaObject;
pub extern fn dos_qabstractitemmodel_create(callbackObject: ?*c_void, metaObject: ?*DosQMetaObject, dObjectCallback: DObjectCallback, callbacks: [*c]DosQAbstractItemModelCallbacks) ?*DosQAbstractItemModel;
pub extern fn dos_qabstractitemmodel_setData(vptr: ?*DosQAbstractItemModel, index: ?*DosQModelIndex, data: ?*DosQVariant, role: c_int) bool;
pub extern fn dos_qabstractitemmodel_roleNames(vptr: ?*DosQAbstractItemModel) ?*DosQHashIntQByteArray;
pub extern fn dos_qabstractitemmodel_flags(vptr: ?*DosQAbstractItemModel, index: ?*DosQModelIndex) c_int;
pub extern fn dos_qabstractitemmodel_headerData(vptr: ?*DosQAbstractItemModel, section: c_int, orientation: c_int, role: c_int) ?*DosQVariant;
pub extern fn dos_qabstractitemmodel_hasChildren(vptr: ?*DosQAbstractItemModel, parentIndex: ?*DosQModelIndex) bool;
pub extern fn dos_qabstractitemmodel_hasIndex(vptr: ?*DosQAbstractItemModel, row: c_int, column: c_int, dosParentIndex: ?*DosQModelIndex) bool;
pub extern fn dos_qabstractitemmodel_canFetchMore(vptr: ?*DosQAbstractItemModel, parentIndex: ?*DosQModelIndex) bool;
pub extern fn dos_qabstractitemmodel_fetchMore(vptr: ?*DosQAbstractItemModel, parentIndex: ?*DosQModelIndex) void;
pub extern fn dos_qabstractitemmodel_beginInsertRows(vptr: ?*DosQAbstractItemModel, parent: ?*DosQModelIndex, first: c_int, last: c_int) void;
pub extern fn dos_qabstractitemmodel_endInsertRows(vptr: ?*DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_beginRemoveRows(vptr: ?*DosQAbstractItemModel, parent: ?*DosQModelIndex, first: c_int, last: c_int) void;
pub extern fn dos_qabstractitemmodel_endRemoveRows(vptr: ?*DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_beginInsertColumns(vptr: ?*DosQAbstractItemModel, parent: ?*DosQModelIndex, first: c_int, last: c_int) void;
pub extern fn dos_qabstractitemmodel_endInsertColumns(vptr: ?*DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_beginRemoveColumns(vptr: ?*DosQAbstractItemModel, parent: ?*DosQModelIndex, first: c_int, last: c_int) void;
pub extern fn dos_qabstractitemmodel_endRemoveColumns(vptr: ?*DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_beginResetModel(vptr: ?*DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_endResetModel(vptr: ?*DosQAbstractItemModel) void;
pub extern fn dos_qabstractitemmodel_dataChanged(vptr: ?*DosQAbstractItemModel, topLeft: ?*const DosQModelIndex, bottomRight: ?*const DosQModelIndex, rolesPtr: [*c]c_int, rolesLength: c_int) void;
pub extern fn dos_qabstractitemmodel_createIndex(vptr: ?*DosQAbstractItemModel, row: c_int, column: c_int, data: ?*c_void) ?*DosQModelIndex;
pub extern fn dos_qobject_qmetaobject() ?*DosQMetaObject;
pub extern fn dos_qobject_create(dObjectPointer: ?*c_void, metaObject: ?*DosQMetaObject, dObjectCallback: DObjectCallback) ?*DosQObject;
pub extern fn dos_qobject_signal_emit(vptr: ?*DosQObject, name: [*c]const u8, parametersCount: c_int, parameters: [*c]?*c_void) void;
pub extern fn dos_qobject_signal_connect(senderVPtr: ?*DosQObject, signal: [*c]const u8, receiverVPtr: ?*DosQObject, method: [*c]const u8, type: c_int) bool;
pub extern fn dos_qobject_signal_disconnect(senderVPtr: ?*DosQObject, signal: [*c]const u8, receiverVPtr: ?*DosQObject, method: [*c]const u8) bool;
pub extern fn dos_qobject_objectName(vptr: ?*const DosQObject) [*c]u8;
pub extern fn dos_qobject_setObjectName(vptr: ?*DosQObject, name: [*c]const u8) void;
pub extern fn dos_qobject_delete(vptr: ?*DosQObject) void;
pub extern fn dos_qobject_deleteLater(vptr: ?*DosQObject) void;
pub extern fn dos_qobject_property(vptr: ?*DosQObject, propertyName: [*c]const u8) ?*DosQVariant;
pub extern fn dos_qobject_setProperty(vptr: ?*DosQObject, propertyName: [*c]const u8, value: ?*DosQVariant) bool;
pub extern fn dos_slot_macro(str: [*c]const u8) [*c]u8;
pub extern fn dos_signal_macro(str: [*c]const u8) [*c]u8;
pub extern fn dos_qobject_connect_static(sender: ?*DosQObject, signal: [*c]const u8, receiver: ?*DosQObject, slot: [*c]const u8, connection_type: enum_DosQtConnectionType) void;
pub extern fn dos_qobject_disconnect_static(sender: ?*DosQObject, signal: [*c]const u8, receiver: ?*DosQObject, slot: [*c]const u8) void;
pub extern fn dos_qmodelindex_create() ?*DosQModelIndex;
pub extern fn dos_qmodelindex_create_qmodelindex(index: ?*DosQModelIndex) ?*DosQModelIndex;
pub extern fn dos_qmodelindex_delete(vptr: ?*DosQModelIndex) void;
pub extern fn dos_qmodelindex_row(vptr: ?*const DosQModelIndex) c_int;
pub extern fn dos_qmodelindex_column(vptr: ?*const DosQModelIndex) c_int;
pub extern fn dos_qmodelindex_isValid(vptr: ?*const DosQModelIndex) bool;
pub extern fn dos_qmodelindex_data(vptr: ?*const DosQModelIndex, role: c_int) ?*DosQVariant;
pub extern fn dos_qmodelindex_parent(vptr: ?*const DosQModelIndex) ?*DosQModelIndex;
pub extern fn dos_qmodelindex_child(vptr: ?*const DosQModelIndex, row: c_int, column: c_int) ?*DosQModelIndex;
pub extern fn dos_qmodelindex_sibling(vptr: ?*const DosQModelIndex, row: c_int, column: c_int) ?*DosQModelIndex;
pub extern fn dos_qmodelindex_assign(l: ?*DosQModelIndex, r: ?*const DosQModelIndex) void;
pub extern fn dos_qmodelindex_internalPointer(vptr: ?*DosQModelIndex) ?*c_void;
pub extern fn dos_qhash_int_qbytearray_create() ?*DosQHashIntQByteArray;
pub extern fn dos_qhash_int_qbytearray_delete(vptr: ?*DosQHashIntQByteArray) void;
pub extern fn dos_qhash_int_qbytearray_insert(vptr: ?*DosQHashIntQByteArray, key: c_int, value: [*c]const u8) void;
pub extern fn dos_qhash_int_qbytearray_value(vptr: ?*const DosQHashIntQByteArray, key: c_int) [*c]u8;
pub extern fn dos_qresource_register(filename: [*c]const u8) void;
pub extern fn dos_qurl_create(url: [*c]const u8, parsingMode: c_int) ?*DosQUrl;
pub extern fn dos_qurl_delete(vptr: ?*DosQUrl) void;
pub extern fn dos_qurl_to_string(vptr: ?*const DosQUrl) [*c]u8;
pub extern fn dos_qurl_isValid(vptr: ?*const DosQUrl) bool;
pub extern fn dos_qdeclarative_qmlregistertype(qmlRegisterType: [*c]const QmlRegisterType) c_int;
pub extern fn dos_qdeclarative_qmlregistersingletontype(qmlRegisterType: [*c]const QmlRegisterType) c_int;
pub extern fn dos_qpointer_create(object: ?*DosQObject) ?*DosQPointer;
pub extern fn dos_qpointer_delete(self: ?*DosQPointer) void;
pub extern fn dos_qpointer_is_null(self: ?*DosQPointer) bool;
pub extern fn dos_qpointer_clear(self: ?*DosQPointer) void;
pub extern fn dos_qpointer_data(self: ?*DosQPointer) ?*DosQObject;
pub const DosQEventLoopProcessEventFlag = enum_DosQEventLoopProcessEventFlag;
pub const DosQtConnectionType = enum_DosQtConnectionType;
