name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master

      - name: get-cmake
        uses: lukka/get-cmake@v3.19.2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.12.1
        with:
          version: 5.15.2
          setup-python: 'true'
          modules: qtcharts qtquick3d
          aqtversion: '>=0.11.1'
          py7zrversion: '>=0.11.3'
          extra: '--external 7z'
          set-env: 'true'
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.py }}

      - name: MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel git unzip mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-cmake mingw-w64-${{ matrix.arch }}-qt5
      
      - name: Deps - Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev -y
          
      - name: Build & Tests
        run: |
          zig build Hello
          zig build Animated
          zig build Cells
          zig build Table
          zig build Layouts
          zig build Particle
          zig build Button
          zig build Splits
