name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install buildtools
        run: |
            sudo apt update
            sudo apt install build-essential libssl1.0-dev qttools5-dev qttools5-dev-tools qtbase5-dev qtpositioning5-dev qtlocation5-dev qtconnectivity5-dev qtmultimedia5-dev qtdeclarative5-dev qtquickcontrols2-5-dev libqt5serialport5-dev libqt5svg5-dev libqt5opengl5-dev libqt5charts5-dev qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtpositioning qml-module-qtlocation qml-module-qtmultimedia qml-module-qtgraphicaleffects qml-module-qtcharts ninja-build cmake -y
      
      - name: Install zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build & Tests
        run: |
          export QT_DEBUG_PLUGINS=1
          zig build Hello -Drelease-safe
