name: Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: mlugg/setup-zig@v2
      
      - name: Install buildtools
        run: |
            sudo apt update
            sudo apt install build-essential qtbase5-dev qtbase5-private-dev \
            qtdeclarative5-dev qtquickcontrols2-5-dev qml-module-qtquick2 \
            qml-module-qtquick-controls2 qml-module-qtquick-window2 cmake -y

      - name: Build & Tests
        run: |
              zig build cmake
              zig build --summary all -freference-trace
