name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install buildtools
        run: |
            sudo apt update
            sudo apt install build-essential libgl1-mesa-dev libxcb-xinerama0 libxkbcommon-x11-0 libpulse-dev ninja-build cmake -y
    
      - name: Install Qt5
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.14.2
          modules: qtcharts
          dir: '${{ github.workspace }}/build/'
      
      - name: Install zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build & Tests
        run: |
          QTDIR="$GITHUB_WORKSPACE/build/Qt/5.15.2/gcc_64" && PATH="${QTDIR}/bin:$PATH" && LDFLAGS=-L${QTDIR}/lib && CPPFLAGS=-I${QTDIR}/include;
          export QT_DEBUG_PLUGINS=1
          export QT_PLUGIN_PATH="${QTDIR}/plugins"
          zig build Hello
