name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install buildtools
        run: |
            sudo apt update
            sudo apt install -f build-essential libdouble-conversion-dev \
            libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev libxext-dev \
            libdrm-dev libx11-dev libudev-dev libinput-dev libts-dev libxcb-xinerama0-dev \
            libxcb-xinerama0 libxkbcommon-dev libxkbcommon-x11-dev libx11-dev libxcb1-dev \
            libx11-xcb-dev libxext-dev libssl1.0-dev qttools5-dev qttools5-dev-tools qtbase5-dev \
            qtpositioning5-dev qtlocation5-dev qtdeclarative5-dev qtquickcontrols2-5-dev libqt5svg5-dev \
            libqt5opengl5-dev libqt5charts5-dev qml-module-qtquick-controls2 qml-module-qtquick-layouts \
            qml-module-qtpositioning qml-module-qtgraphicaleffects qml-module-qtcharts ninja-build cmake -y
      
      - name: Install zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build & Tests
        run: CC="zig cc $@" CXX="zig c++ $@" zig build -Drelease-safe && ls zig-cache/bin
