name: Linux

on: [push, pull_request]

jobs:
  build:
    container: fedora:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install buildtools
        run: |
          uname -a
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make gcc-c++
          dnf -y upgrade git
      
      - name: Install zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: get-cmake
        uses: lukka/get-cmake@v3.19.2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtcharts qtquick3d
          aqtversion: '>=0.11.1'
          py7zrversion: '>=0.11.3'
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Build & Tests
        run: |
          zig build Hello
          zig build Animated
          zig build Cells
          zig build Table
          zig build Layouts
          zig build Particle
          zig build Button
          zig build Splits
