name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install buildtools
        run: |
            sudo apt-get update
            sudo apt-get install build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev qt5-default cmake -y
    
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2
      
      - name: Install zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build & Tests
        run: |
          zig build Hello
          zig build Animated
          zig build Cells
          zig build Table
          zig build Layouts
          zig build Particle
          zig build Button
          zig build Splits
