name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install
        run: brew install qt gdb zig --HEAD

      - name: Build & Tests
        run: |
          QTDIR="/usr/local/opt/qt/" && PATH="${QTDIR}/bin:$PATH" && LDFLAGS=-L${QTDIR}/lib && CPPFLAGS=-I${QTDIR}/include;
          zig build Animated
          zig build Button
          zig build Cells          
          zig build Hello
          zig build Layouts
          zig build Particle
          zig build Splits
          zig build Table
