name: MacOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: mlugg/setup-zig@v2
      - name: Install
        run: brew install cmake
      - uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          dir: '${{ github.workspace }}/build/'
          
      - name: Build & Tests
        run: |
            QTDIR="$GITHUB_WORKSPACE/build/Qt/6.8.2/clang_64" && \
            PATH="${QTDIR}/bin:$PATH" && LDFLAGS=-L${QTDIR}/lib && \
            CPPFLAGS=-I${QTDIR}/include && \
            zig build cmake && \
            zig build --summary all -freference-trace
