name: MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Install
        run: brew install cmake

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.2
          dir: '${{ github.workspace }}/build/'
          
      - name: Build & Tests
        run: |
            QTDIR="$GITHUB_WORKSPACE/build/Qt/5.15.2/clang_64" && \
            PATH="${QTDIR}/bin:$PATH" && LDFLAGS=-L${QTDIR}/lib && \
            CPPFLAGS=-I${QTDIR}/include && \
            zig build -Doptimize=ReleaseSafe && ls zig-out/bin
