name: MSYS2 (MingW)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64, prefix: /mingw64 },
          { msystem: MINGW32, arch: i686, prefix: /mingw32   }
        ]
    
    steps:
      - uses: actions/checkout@v2
        with:
          path: temp
          submodules: recursive
          fetch-depth: 0
      
      - name: Install zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          path-type: inherit
          install: git base-devel binutils unzip mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-ninja mingw-w64-${{ matrix.arch }}-cmake mingw-w64-${{ matrix.arch }}-qt5
          update: true
      
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: Build & Tests
        shell: msys2 {0}
        if: matrix.arch == 'i686'
        run: |
          cd /C/_
          zig build -Drelease-safe -Dtarget=i386-windows-gnu
        else:
        run: |
          cd /C/_
          zig build -Drelease-safe -Dtarget=native-windows-gnu
