name: MSYS2 (MingW)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: CLANG64, arch: x86_64, prefix: /clang64 },
          { msystem: CLANG32, arch: i686, prefix: /clang32   }
        ]
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: temp
          submodules: recursive
          fetch-depth: 0
      
      - uses: mlugg/setup-zig@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          path-type: inherit
          install: git base-devel binutils unzip mingw-w64-clang-${{ matrix.arch }}-toolchain mingw-w64-clang-${{ matrix.arch }}-cmake mingw-w64-clang-${{ matrix.arch }}-qt5-base mingw-w64-clang-${{ matrix.arch }}-qt5-declarative
          update: true
      
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: Build & Tests (x86)
        shell: msys2 {0}
        if: ${{ matrix.arch == 'i686' }}
        run: |
            cd /C/_
            zig build cmake
            zig build -Dtarget=x86-windows --summary all -freference-trace
        
      - name: Build & Tests (x86_x64)
        shell: msys2 {0}
        if: ${{ matrix.arch == 'x86_64' }}
        run: |
            cd /C/_
            zig build cmake
            zig build -Dtarget=x86_64-windows --summary all -freference-trace
